# Generated by Django 5.2.6 on 2026-02-12 22:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0001_initial"),
        ("product", "0005_product_discount_percentage_product_is_active_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                    ("FAILED", "Failed"),
                    ("REFUNDED", "Refunded"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["order", "status"], name="payment_pay_order_i_b37863_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["created_at"], name="payment_pay_created_671024_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockdeductionlog",
            index=models.Index(
                fields=["order", "action"], name="payment_sto_order_i_fe9a87_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockdeductionlog",
            index=models.Index(
                fields=["created_at"], name="payment_sto_created_e66ecc_idx"
            ),
        ),
    ]
